version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: "Dockerfile"
    restart: always
    container_name: desafio-temperatura
    ports:
      - "8001:8001"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
