version: '3.8'

services:
  app:
    image: beriloqueiroz/desafio-temperatura-por-cep:latest
    build: 
      context: ./
      dockerfile: "Dockerfile"
    restart: always
    container_name: desafio-temperatura
    ports:
      - "8080:8080"
